SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS exercise_set;
DROP TABLE IF EXISTS workout_session_exercise;
DROP TABLE IF EXISTS workout_session;
DROP TABLE IF EXISTS workout_template_exercise;
DROP TABLE IF EXISTS workout_template;
DROP TABLE IF EXISTS program;
DROP TABLE IF EXISTS exercise_equipment;
DROP TABLE IF EXISTS exercise_muscle;
DROP TABLE IF EXISTS exercise;
DROP TABLE IF EXISTS equipment;
DROP TABLE IF EXISTS muscle_group;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS difficulty;
DROP TABLE IF EXISTS user;

SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE user (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  theme ENUM('light', 'dark', 'system') NOT NULL DEFAULT 'system',
  last_login_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE difficulty (
  id TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE category (
  id TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE muscle_group (
  id SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE equipment (
  id SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE exercise (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  slug VARCHAR(100) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  category_id TINYINT UNSIGNED NOT NULL,
  difficulty_id TINYINT UNSIGNED NOT NULL,
  CONSTRAINT fk_exercise_category
    FOREIGN KEY (category_id) REFERENCES category(id)
    ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_exercise_difficulty
    FOREIGN KEY (difficulty_id) REFERENCES difficulty(id)
    ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE INDEX idx_exercise_name ON exercise(name);

CREATE TABLE exercise_muscle (
  exercise_id INT UNSIGNED NOT NULL,
  muscle_group_id SMALLINT UNSIGNED NOT NULL,
  role ENUM('primary', 'secondary') NOT NULL,
  PRIMARY KEY (exercise_id, muscle_group_id),
  CONSTRAINT fk_exercise_muscle_exercise
    FOREIGN KEY (exercise_id) REFERENCES exercise(id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_exercise_muscle_muscle_group
    FOREIGN KEY (muscle_group_id) REFERENCES muscle_group(id)
    ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE exercise_equipment (
  exercise_id INT UNSIGNED NOT NULL,
  equipment_id SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (exercise_id, equipment_id),
  CONSTRAINT fk_exercise_equipment_exercise
    FOREIGN KEY (exercise_id) REFERENCES exercise(id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_exercise_equipment_equipment
    FOREIGN KEY (equipment_id) REFERENCES equipment(id)
    ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE program (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  user_id INT UNSIGNED NOT NULL,
  name VARCHAR(100) NOT NULL,
  description TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_program_user
    FOREIGN KEY (user_id) REFERENCES user(id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE workout_template (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  program_id INT UNSIGNED NOT NULL,
  name VARCHAR(100) NOT NULL,
  estimated_duration_minutes SMALLINT UNSIGNED NULL,
  position SMALLINT UNSIGNED NOT NULL,
  CONSTRAINT uq_workout_template_position UNIQUE (program_id, position),
  CONSTRAINT fk_workout_template_program
    FOREIGN KEY (program_id) REFERENCES program(id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE workout_template_exercise (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  workout_template_id INT UNSIGNED NOT NULL,
  exercise_id INT UNSIGNED NOT NULL,
  position SMALLINT UNSIGNED NOT NULL,
  target_sets SMALLINT UNSIGNED NOT NULL,
  target_reps SMALLINT UNSIGNED NULL,
  target_weight_kg DECIMAL(5,2) NULL,
  target_duration_seconds SMALLINT UNSIGNED NULL,
  rest_seconds SMALLINT UNSIGNED NULL,
  CONSTRAINT uq_workout_template_exercise
    UNIQUE (workout_template_id, exercise_id),
  CONSTRAINT uq_workout_template_exercise_position UNIQUE (workout_template_id, position),
  CONSTRAINT fk_workout_template_exercise_template
    FOREIGN KEY (workout_template_id) REFERENCES workout_template(id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_workout_template_exercise_exercise
    FOREIGN KEY (exercise_id) REFERENCES exercise(id)
    ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE workout_session (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  user_id INT UNSIGNED NOT NULL,
  workout_template_id INT UNSIGNED NULL,
  source_workout_session_id INT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  started_at DATETIME NULL,
  ended_at DATETIME NULL,
  status ENUM('prepared', 'in_progress', 'completed') NOT NULL DEFAULT 'prepared',
  notes TEXT NULL,
  CONSTRAINT fk_workout_session_user
    FOREIGN KEY (user_id) REFERENCES user(id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_workout_session_template
    FOREIGN KEY (workout_template_id) REFERENCES workout_template(id)
    ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_workout_session_source
    FOREIGN KEY (source_workout_session_id) REFERENCES workout_session(id)
    ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE workout_session_exercise (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  workout_session_id INT UNSIGNED NOT NULL,
  exercise_id INT UNSIGNED NOT NULL,
  position SMALLINT UNSIGNED NOT NULL,
  target_sets SMALLINT UNSIGNED NULL,
  target_reps SMALLINT UNSIGNED NULL,
  target_weight_kg DECIMAL(5,2) NULL,
  target_duration_seconds SMALLINT UNSIGNED NULL,
  rest_seconds SMALLINT UNSIGNED NULL,
  CONSTRAINT uq_workout_session_exercise UNIQUE (workout_session_id, exercise_id),
  CONSTRAINT uq_workout_session_exercise_position UNIQUE (workout_session_id, position),
  CONSTRAINT fk_workout_session_exercise_session
    FOREIGN KEY (workout_session_id) REFERENCES workout_session(id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_workout_session_exercise_exercise
    FOREIGN KEY (exercise_id) REFERENCES exercise(id)
    ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE exercise_set (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  workout_session_exercise_id INT UNSIGNED NOT NULL,
  set_number SMALLINT UNSIGNED NOT NULL,
  repetitions SMALLINT UNSIGNED NULL,
  weight_kg DECIMAL(5,2) NULL,
  duration_seconds SMALLINT UNSIGNED NULL,
  is_completed BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT uq_exercise_set_number UNIQUE (workout_session_exercise_id, set_number),
  CONSTRAINT fk_exercise_set_session_exercise
    FOREIGN KEY (workout_session_exercise_id) REFERENCES workout_session_exercise(id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

-- Donnees indispensables au fonctionnement du catalogue
START TRANSACTION;

INSERT INTO difficulty (id, name) VALUES
  (1, 'Débutant'),
  (2, 'Intermédiaire'),
  (3, 'Avancé');

INSERT INTO category (id, name) VALUES
  (1, 'Pectoraux'),
  (2, 'Dos'),
  (3, 'Épaules'),
  (4, 'Bras'),
  (5, 'Jambes'),
  (6, 'Abdominaux'),
  (7, 'Cardio'),
  (8, 'Étirements');

INSERT INTO muscle_group (id, name) VALUES
  (1, 'Pectoraux'),
  (2, 'Épaules'),
  (3, 'Triceps'),
  (4, 'Biceps'),
  (5, 'Avant-bras'),
  (6, 'Abdominaux'),
  (7, 'Obliques'),
  (8, 'Dorsaux'),
  (9, 'Trapèzes'),
  (10, 'Lombaires'),
  (11, 'Fessiers'),
  (12, 'Quadriceps'),
  (13, 'Ischio-jambiers'),
  (14, 'Mollets'),
  (15, 'Adducteurs');

INSERT INTO equipment (id, name) VALUES
  (1, 'Machine'),
  (2, 'Poulie'),
  (3, 'Haltères'),
  (4, 'Barre'),
  (5, 'Poids du corps'),
  (6, 'Cardio');

INSERT INTO exercise (id, slug, name, description, category_id, difficulty_id) VALUES
  (1, 'seated-chest-press', 'Développé poitrine à la machine', '1. Règle le siège pour que les poignées soient à hauteur de ta poitrine.\n2. Assieds-toi le dos droit et les pieds bien ancrés au sol.\n3. Pousse les poignées vers l''avant jusqu''à avoir les bras tendus, sans verrouiller les coudes.\n4. Reviens lentement à la position de départ en contrôlant le mouvement.', 1, 1),
  (2, 'incline-chest-press-machine', 'Développé poitrine incliné à la machine', '1. Règle le siège et le dossier pour que les poignées arrivent au niveau de la poitrine.\n2. Assieds-toi et saisis les poignées avec une prise ferme.\n3. Pousse les poignées vers l''avant jusqu''à avoir les bras presque tendus.\n4. Reviens lentement à la position de départ en gardant le contrôle.', 1, 1),
  (3, 'butterflies', 'Écartés à la machine (pec deck)', '1. Règle le siège de la machine pour que les poignées soient à hauteur de ta poitrine.\n2. Assieds-toi dos plaqué au dossier et saisis les poignées, coudes légèrement fléchis.\n3. Souffle en rapprochant les poignées devant toi, en gardant les coudes dans la même position.\n4. Inspire en revenant lentement à la position de départ, sans laisser les plaques s''entrechoquer.', 1, 1),
  (4, 'chest-pulldown', 'Tirage vertical poitrine', '1. Règle le siège et le boudin des cuisses, et assure-toi que tes pieds sont bien à plat au sol.\n2. Saisis la barre en prise large, paumes vers l''avant.\n3. Tire la barre vers le bas jusqu''à ce qu''elle effleure le haut de la poitrine, dos droit et coudes vers les côtés.\n4. Laisse remonter la barre lentement à la position de départ en contrôlant le mouvement.', 2, 1),
  (5, 'close-grip-chest-pulldown', 'Tirage vertical poitrine prise serrée', '1. Règle le siège et cale tes genoux sous le boudin.\n2. Saisis la barre en prise serrée, paumes vers toi.\n3. Tire la barre vers le bas jusqu''à ce qu''elle touche le haut de la poitrine, en gardant le dos droit.\n4. Reviens lentement à la position de départ en contrôlant le mouvement.', 2, 1),
  (6, 'seated-row-machine', 'Tirage horizontal assis à la machine', '1. Règle le siège et le cale-pieds selon ta taille.\n2. Assieds-toi le dos droit et saisis les poignées avec une prise ferme.\n3. Tire les poignées vers ton buste en gardant les coudes près du corps.\n4. Reviens lentement à la position de départ sans relâcher la tension.', 2, 1),
  (7, 'seated-cable-back-rows', 'Tirage horizontal assis à la poulie', '1. Assieds-toi sur la machine de tirage horizontal, pieds calés sur les repose-pieds.\n2. Saisis la poignée à deux mains en gardant le dos droit.\n3. Tire la poignée vers ton ventre en rapprochant les omoplates.\n4. Reviens lentement à la position de départ en contrôlant le mouvement.', 2, 1),
  (8, 'seated-dumbbell-overhead-shoulder-press', 'Développé épaules avec haltères', '1. Assieds-toi sur un banc avec dossier, les pieds bien ancrés au sol.\n2. Tiens un haltère dans chaque main à hauteur des épaules, paumes vers l''avant.\n3. Pousse les haltères vers le haut jusqu''à avoir les bras tendus, sans verrouiller les coudes.\n4. Redescends lentement les haltères à la position de départ.', 3, 2),
  (9, 'machine-shoulder-press', 'Développé épaules à la machine', '1. Règle le siège de la machine pour que les poignées soient à hauteur de tes épaules.\n2. Assieds-toi le dos droit et les pieds bien ancrés au sol.\n3. Saisis les poignées paumes vers l''avant et pousse vers le haut jusqu''à tendre les bras.\n4. Reviens lentement à la position de départ sans laisser les plaques se toucher.', 3, 1),
  (10, 'dumbbell-lateral-raises', 'Élévations latérales avec haltères', '1. Debout, pieds à largeur d''épaules, un haltère dans chaque main le long du corps.\n2. Garde les coudes légèrement fléchis et monte les bras sur les côtés jusqu''à l''horizontale.\n3. Redescends lentement les haltères à la position de départ en contrôlant le mouvement.', 3, 1),
  (11, 'face-pull', 'Face pull', '1. Règle la poulie à hauteur de ton visage et saisis les poignées en prise pronation.\n2. Recule d''un pas pour mettre le câble en tension et place les pieds à largeur d''épaules.\n3. Tire les poignées vers ton visage en gardant les coudes hauts et ouverts.\n4. Reviens lentement à la position de départ en contrôlant le mouvement.', 3, 1),
  (12, 'alternating-dumbbell-biceps-curl', 'Curl biceps alterné avec haltères', '1. Tiens un haltère dans chaque main, paumes vers l''avant et bras tendus le long du corps.\n2. Fléchis le coude droit et monte l''haltère vers l''épaule en gardant le coude collé au corps.\n3. Redescends lentement l''haltère à la position de départ, puis répète avec le bras gauche.', 4, 1),
  (13, 'dumbbell-hammer-biceps-curl', 'Curl marteau avec haltères', '1. Tiens-toi debout, dos droit, pieds à largeur d''épaules.\n2. Tiens un haltère dans chaque main, paumes tournées vers l''intérieur.\n3. Garde les coudes collés au corps et monte les haltères vers les épaules.\n4. Redescends lentement les haltères à la position de départ.', 4, 1),
  (14, 'triceps-pushdown', 'Extension des triceps à la poulie', '1. Règle la poulie en position haute et accroche la barre droite.\n2. Place-toi debout, pieds à largeur d''épaules, et saisis la barre paumes vers le bas.\n3. Garde les coudes collés au corps et pousse la barre vers le bas jusqu''à tendre complètement les bras.\n4. Laisse remonter lentement la barre à la position de départ sans bouger les coudes.', 4, 1),
  (15, 'dips-machine', 'Dips à la machine', '1. Règle le siège et les appuis pour que tes bras forment un angle de 90 degrés au départ.\n2. Saisis les poignées avec une prise ferme et confortable.\n3. Pousse vers le bas jusqu''à avoir les bras presque tendus, en gardant le contrôle.\n4. Reviens lentement à la position de départ sans verrouiller les coudes.', 4, 1),
  (16, 'leg-press', 'Presse à cuisses', '1. Règle le siège et le dossier pour que tes genoux forment un angle de 90 degrés une fois les pieds sur le plateau.\n2. Place les pieds à largeur d''épaules sur le plateau et vérifie qu''ils sont bien en appui.\n3. Pousse le plateau en tendant les jambes, mais sans verrouiller les genoux.\n4. Reviens lentement à la position de départ en contrôlant le mouvement.', 5, 1),
  (17, 'seated-leg-curl', 'Leg curl assis', '1. Règle la machine pour que le boudin se place juste au-dessus de tes chevilles.\n2. Assieds-toi et vérifie que ton dos est bien plaqué contre le dossier.\n3. Attrape les poignées et fléchis les genoux en ramenant le boudin vers tes fessiers.\n4. Reviens lentement à la position de départ sans laisser les plaques taper.', 5, 1),
  (18, 'lying-leg-curls', 'Leg curl allongé', '1. Allonge-toi à plat ventre sur la machine à leg curl et règle le boudin au-dessus de tes chevilles.\n2. Attrape les poignées latérales pour te stabiliser et aligne tes genoux avec l''axe de la machine.\n3. Fléchis les genoux en montant le boudin vers les fessiers, avec un mouvement contrôlé.\n4. Redescends lentement les jambes à la position de départ sans lâcher la charge brutalement.', 5, 1),
  (19, 'seated-leg-extensions', 'Extension des jambes', '1. Règle le siège et le dossier pour que tes genoux soient alignés avec l''axe de la machine.\n2. Place tes pieds sous les boudins rembourrés et vérifie que tes chevilles sont bien installées.\n3. Tends lentement les jambes jusqu''à les avoir presque droites, sans verrouiller les genoux.\n4. Reviens à la position de départ de façon contrôlée, en gardant la tension sur les quadriceps.', 5, 1),
  (20, 'barbell-hip-thrust', 'Hip thrust à la barre', '1. Assieds-toi au sol, le haut du dos calé contre un banc.\n2. Fais rouler la barre sur tes hanches et vérifie qu''elle est bien centrée.\n3. Pieds à plat et genoux fléchis, pousse les hanches vers le haut jusqu''à ce que le corps forme une ligne droite des épaules aux genoux.\n4. Redescends lentement les hanches au sol et recommence.', 5, 2),
  (21, 'box-squat', 'Squat sur box', '1. Place une box derrière toi, à une hauteur adaptée.\n2. Tiens-toi debout, pieds écartés à la largeur des épaules.\n3. Descends en contrôlant jusqu''à ce que les fessiers touchent la box.\n4. Pousse dans les talons pour revenir en position de départ.', 5, 1),
  (22, 'goblet-squats', 'Squat goblet', '1. Tiens un haltère à la verticale avec les deux mains, devant ta poitrine.\n2. Place les pieds à la largeur des épaules, pointes légèrement ouvertes vers l''extérieur.\n3. Descends les hanches vers l''arrière et vers le bas, buste droit et genoux dans l''axe des pieds.\n4. Pousse dans les talons pour revenir en position de départ.', 5, 1),
  (23, 'seated-calf-raises', 'Extension des mollets assis', '1. Assieds-toi à la machine à mollets, les pieds posés sur la plateforme.\n2. Place les coussinets sur tes cuisses et règle la hauteur si besoin.\n3. Monte les talons le plus haut possible en gardant l''avant des pieds sur la plateforme.\n4. Redescends lentement les talons jusqu''à sentir un bon étirement dans les mollets.', 5, 1),
  (24, 'plank', 'Gainage (planche)', '1. Pose les avant-bras et la pointe des pieds au sol, en veillant à ce que les coudes soient à l''aplomb des épaules.\n2. Garde le corps en ligne droite de la tête aux talons, sans laisser les hanches s''affaisser ni remonter.\n3. Contracte les abdominaux et tiens la position en respirant de façon contrôlée.', 6, 1),
  (25, 'side-plank', 'Gainage latéral', '1. Allonge-toi sur le côté, jambes tendues et superposées.\n2. Pose l''avant-bras au sol, le coude à l''aplomb de l''épaule.\n3. Monte les hanches jusqu''à former une ligne droite des pieds à la tête.\n4. Tiens la position en veillant à ne pas laisser les hanches descendre.', 6, 1),
  (26, 'dead-bug', 'Dead bug', '1. Allonge-toi sur le dos, jambes levées et genoux fléchis à 90 degrés.\n2. Tends les bras vers le plafond en gardant le bas du dos plaqué au sol.\n3. Descends lentement le bras droit et la jambe gauche vers le sol, sans le toucher.\n4. Reviens en position de départ et recommence avec le bras gauche et la jambe droite.', 6, 1),
  (27, 'neutral-grip-pulldown', 'Tirage vertical poitrine en prise neutre', '1. Règle le siège et le boudin d''appui pour les cuisses selon ta taille.\n2. Saisis la barre en prise neutre, paumes face à face.\n3. Tire la barre vers le bas jusqu''à ce qu''elle touche le haut de la poitrine, en gardant le dos droit.\n4. Laisse remonter la barre lentement à la position de départ, en contrôlant.', 2, 1),
  (28, 'upright-row', 'Tirage menton à la barre', '1. 1. Tiens-toi debout, pieds à la largeur des épaules, et saisis la barre en pronation, les mains un peu plus serrées que les épaules.\n2. 2. Garde le dos droit et monte la barre en la gardant proche du corps.\n3. 3. Amène les coudes vers le haut et vers l''extérieur jusqu''à ce que la barre arrive à hauteur de la poitrine.\n4. 4. Redescends la barre lentement en position de départ, en contrôlant le mouvement.', 3, 2),
  (29, 'barbell-squat', 'Squat à la barre', '1. Place la barre sur le haut du dos et saisis-la, mains un peu plus larges que les épaules.\n2. Garde le buste droit et la sangle abdominale gainée pendant que tu descends les hanches vers l''arrière et vers le bas, comme pour t''asseoir.\n3. Descends jusqu''à ce que les cuisses soient au moins parallèles au sol, puis pousse dans les talons pour revenir en position de départ.', 5, 2),
  (30, 'bulgarian-split-squat', 'Fente bulgare', '1. Pose un pied derrière toi sur un banc ou une plateforme surélevée.\n2. Avance l''autre pied d''un pas, en veillant à garder le buste droit.\n3. Descends lentement le genou arrière vers le sol, en gardant le genou avant dans l''axe de la cheville.\n4. Pousse dans le talon du pied avant pour revenir en position de départ.', 5, 2),
  (31, 'barbell-bench-press', 'Développé couché', '1. Allonge-toi sur le banc, les pieds bien ancrés au sol.\n2. Saisis la barre, mains un peu plus larges que les épaules.\n3. Descends la barre lentement jusqu''à ce qu''elle effleure la poitrine.\n4. Pousse la barre vers le haut jusqu''à tendre complètement les bras.', 1, 2),
  (32, 'dumbbell-bench-press', 'Développé couché aux haltères', '1. Allonge-toi sur le dos sur un banc plat, un haltère dans chaque main.\n2. Place les haltères à hauteur de la poitrine, coudes fléchis à 90 degrés.\n3. Pousse les haltères vers le haut jusqu''à tendre complètement les bras.\n4. Redescends lentement les haltères en position de départ.', 1, 2),
  (33, 'incline-dumbbell-press', 'Développé incliné aux haltères', '1. Règle le banc sur une inclinaison de 30 à 45 degrés.\n2. Assieds-toi et pose fermement les pieds au sol.\n3. Saisis les haltères en prise neutre et amène-les à hauteur de la poitrine.\n4. Pousse les haltères vers le haut jusqu''à avoir les bras presque tendus, puis redescends lentement.', 1, 2),
  (34, 'dumbbell-flyes', 'Écartés aux haltères', '1. Allonge-toi sur le dos sur un banc plat, un haltère dans chaque main.\n2. Tends les bras vers le haut, paumes face à face et coudes légèrement fléchis.\n3. Descends lentement les haltères sur les côtés en décrivant un grand arc de cercle, jusqu''à sentir un étirement dans les pectoraux.\n4. Reviens en position de départ en contractant les pectoraux, puis recommence.', 1, 1),
  (35, 'barbell-row', 'Tirage horizontal à la barre (rowing barre)', '1. Place les pieds à la largeur des épaules et saisis la barre en pronation.\n2. Penche le buste vers l''avant en gardant le dos droit et les genoux légèrement fléchis.\n3. Tire la barre vers le ventre, en gardant les coudes proches du corps.\n4. Redescends la barre en contrôlant, puis recommence.', 2, 2),
  (36, 'dumbbell-row', 'Tirage horizontal aux haltères (rowing haltères)', '1. 1. Tiens-toi debout, pieds à la largeur des épaules, un haltère dans chaque main.\n2. 2. Penche le buste vers l''avant en partant des hanches, dos droit et genoux légèrement fléchis.\n3. 3. Bras tendus vers le bas, tire les haltères vers la taille en gardant les coudes proches du corps.\n4. 4. Redescends les haltères en contrôlant, puis recommence le mouvement.', 2, 1),
  (37, 'barbell-overhead-press', 'Développé militaire à la barre', '1. Place les pieds à la largeur des épaules et saisis la barre, mains un peu plus larges que les épaules.\n2. Monte la barre à hauteur de la poitrine en veillant à garder les poignets droits.\n3. Pousse la barre vers le haut jusqu''à tendre complètement les bras, en gardant la sangle abdominale gainée.\n4. Redescends la barre lentement en position de départ, en contrôlant le mouvement.', 3, 2),
  (38, 'cable-lateral-raises', 'Élévations latérales à la poulie', '1. Règle la poulie sur la position la plus basse et saisis la poignée d''une main.\n2. Place-toi de côté par rapport à la machine, pieds écartés à la largeur des épaules.\n3. Monte le bras sur le côté jusqu''à hauteur d''épaule, en gardant le coude légèrement fléchi.\n4. Redescends lentement le bras en position de départ, puis recommence.', 3, 1),
  (39, 'barbell-biceps-curl', 'Curl biceps à la barre', '1. Tiens-toi debout, les pieds à largeur d''épaules.\n2. Saisis la barre en supination, paumes vers le haut, les coudes près du corps.\n3. Monte la barre vers les épaules en gardant les coudes immobiles.\n4. Redescends la barre lentement jusqu''à la position de départ.', 4, 1),
  (40, 'overhead-triceps-extension', 'Extension des triceps au-dessus de la tête', '1. Prends un haltère à deux mains et monte-le au-dessus de la tête, les coudes près des oreilles.\n2. Descends l''haltère derrière la tête en pliant les coudes, bras bien stables.\n3. Tends les bras de nouveau vers le haut pour revenir à la position de départ.', 4, 2),
  (41, 'standing-calf-raises', 'Extension des mollets debout', '1. 1. Tiens-toi debout, les pieds à largeur d''épaules et les pointes de pieds vers l''avant.\n2. 2. Garde le dos droit et les abdominaux gainés pendant que tu montes lentement sur la pointe des pieds.\n3. 3. Tiens la position haute une seconde, puis redescends les talons en contrôlant.', 5, 1),
  (42, 'bodyweight-squat', 'Squat au poids du corps', '1. Tiens-toi debout, les pieds à largeur d''épaules.\n2. Descends lentement les hanches comme pour t''asseoir, la poitrine bien haute.\n3. Descends jusqu''à ce que les cuisses soient parallèles au sol.\n4. Pousse dans les talons pour revenir à la position de départ.', 5, 1),
  (43, 'hack-squat', 'Squat à la machine hack verticale', '1. Place les pieds à largeur d''épaules sur la plateforme de la machine à hack squat.\n2. Descends lentement en pliant les genoux jusqu''à ce que les cuisses soient parallèles au sol.\n3. Pousse dans les talons pour revenir à la position de départ en gardant le dos droit.', 5, 2),
  (44, 'deadlift', 'Soulevé de terre', '1. Place les pieds à hauteur des épaules et attrape la barre en pronation.\n2. Garde le dos droit et soulève la barre en dépliant les hanches et les genoux.\n3. Garde la barre près du corps pendant que tu te redresses complètement.\n4. Repose la barre au sol en contrôlant, sans casser ta position.', 5, 2),
  (45, 'pull-ups', 'Tractions', '1. Attrape la barre en pronation, paumes vers l''avant, à largeur d''épaules.\n2. Suspends-toi bras tendus, puis tire ton corps vers le haut jusqu''à passer le menton au-dessus de la barre.\n3. Redescends en contrôlant jusqu''à la position de départ.', 2, 3),
  (46, 'treadmill', 'Tapis de course', '1. Règle la vitesse et l''inclinaison du tapis à un niveau confortable.\n2. Garde une posture droite et relâchée pendant que tu marches ou que tu cours.\n3. Adopte une foulée naturelle, en posant le talon en douceur.\n4. Garde un rythme constant et respire régulièrement.', 7, 1),
  (47, 'elliptical', 'Vélo elliptique', '1. Règle la résistance et l''inclinaison à un niveau confortable.\n2. Pose les pieds sur les pédales et attrape les poignées.\n3. Lance le mouvement elliptique des jambes en gardant le buste droit.\n4. Augmente progressivement la vitesse et la résistance selon ton niveau de forme.', 7, 1),
  (48, 'stationary-bike', 'Vélo d''appartement', '1. Règle la hauteur de selle pour que tes jambes restent légèrement fléchies au pédalage.\n2. Pose les pieds sur les pédales et serre les sangles de sécurité si besoin.\n3. Commence à pédaler à un rythme confortable, le dos droit et les épaules relâchées.', 7, 1),
  (49, 'rowing-machine', 'Rameur (cardio)', '1. Règle le siège et la résistance à ton niveau.\n2. Cale les pieds sur les repose-pieds et attrape la poignée à deux mains.\n3. Pousse avec les jambes tout en tirant la poignée vers la poitrine.\n4. Reviens à la position de départ en tendant les bras puis en pliant les genoux.', 7, 2),
  (50, 'burpees', 'Burpees', '1. Pars debout, les pieds à largeur d''épaules.\n2. Descends en position accroupie et pose les mains au sol devant toi.\n3. Envoie les pieds en arrière d''un saut pour te retrouver en position de gainage (planche).\n4. Enchaîne une pompe, puis ramène les pieds en avant d''un saut et relève-toi en sautant.', 7, 2),
  (51, 'crunch', 'Crunch abdominal', '1. Allonge-toi sur le dos, genoux pliés et pieds à plat au sol.\n2. Pose les mains légèrement derrière la tête, sans tirer sur la nuque.\n3. Contracte les abdominaux et décolle les épaules du sol en gardant le bas du dos plaqué au sol.\n4. Redescends lentement les épaules au sol et recommence.', 6, 1),
  (52, 'legs-up-crunch', 'Crunch jambes relevées', '1. Allonge-toi sur le dos, les jambes relevées et les genoux légèrement fléchis.\n2. Pose les mains derrière la tête en gardant les coudes ouverts.\n3. Contracte les abdominaux et décolle les épaules du sol en rapprochant la poitrine des genoux.\n4. Redescends lentement les épaules au sol sans laisser tomber les jambes.', 6, 1),
  (53, 'scissor-kicks', 'Ciseaux', '1. Allonge-toi sur le dos, les jambes tendues.\n2. Glisse les mains sous les fessiers pour te soutenir.\n3. Décolle les deux jambes de quelques centimètres du sol.\n4. Croise les jambes en alternance, l''une par-dessus l''autre, en gardant les abdominaux contractés.', 6, 1),
  (54, 'sit-ups', 'Relevé de buste', '1. Allonge-toi sur le dos, genoux pliés et pieds à plat au sol.\n2. Pose les mains derrière la tête sans entrelacer les doigts.\n3. Monte le buste vers les genoux avec les abdominaux, en gardant le dos droit.\n4. Redescends lentement à la position de départ sans laisser retomber le corps.', 6, 1),
  (55, 'russian-twist', 'Russian twist', '1. Assieds-toi au sol, genoux pliés et pieds légèrement décollés.\n2. Incline le buste en arrière en gardant le dos droit, à environ 45 degrés.\n3. Fais tourner le buste d''un côté en amenant les mains ou une charge vers le sol, puis recommence de l''autre côté.', 6, 1),
  (56, 'glute-bridge', 'Pont fessier', '1. Allonge-toi sur le dos, genoux pliés et pieds posés au sol.\n2. Place les bras le long du corps, paumes vers le sol.\n3. Pousse dans les talons et monte les hanches jusqu''à aligner les épaules, les hanches et les genoux.\n4. Tiens la position un instant, puis redescends lentement les hanches au sol.', 5, 1),
  (57, 'side-plank-rotation', 'Gainage latéral avec rotation', '1. Place-toi en gainage latéral, l''avant-bras au sol et le corps bien aligné.\n2. Monte les hanches pour former une ligne droite des pieds à la tête.\n3. Tends le bras libre vers le plafond, puis passe-le lentement sous le buste en faisant tourner le tronc.\n4. Reviens à la position de départ et recommence avant de changer de côté.', 6, 2),
  (58, 'superman', 'Superman', '1. Allonge-toi sur le ventre, bras tendus devant toi et jambes tendues.\n2. Inspire et décolle en même temps les bras, la poitrine et les jambes du sol, en gardant la nuque alignée.\n3. Tiens la position quelques secondes, en sentant la contraction dans le bas du dos.\n4. Expire et redescends lentement les bras, la poitrine et les jambes au sol.', 6, 1),
  (59, 'incline-barbell-bench-press', 'Développé couché incliné à la barre', '1. Règle le banc sur une inclinaison de 30 à 45 degrés.\n2. Allonge-toi sur le banc, pieds bien ancrés au sol.\n3. Saisis la barre avec une prise légèrement plus large que les épaules.\n4. Descends la barre vers le haut de la poitrine, puis pousse vers le haut jusqu''à tendre les bras.', 1, 2),
  (60, 'romanian-deadlift', 'Soulevé de terre roumain', '1. Debout, pieds à hauteur des épaules, tiens la barre devant tes cuisses.\n2. Garde le dos droit et descends la barre en la faisant glisser le long des jambes, genoux légèrement fléchis.\n3. Arrête-toi quand tu sens l''étirement dans les ischio-jambiers, puis reviens à la position de départ.', 5, 2),
  (61, 'front-squat', 'Squat avant', '1. Place la barre sur l''avant de tes épaules, bras croisés pour la maintenir.\n2. Garde les pieds à largeur d''épaules et descends lentement en pliant les genoux, dos droit.\n3. Descends jusqu''à ce que tes cuisses soient parallèles au sol, puis pousse dans les talons pour revenir à la position de départ.', 5, 2),
  (62, 'step-up', 'Step-up avec charge', '1. Place un banc stable devant toi.\n2. Tiens un haltère dans chaque main, bras le long du corps.\n3. Monte un pied sur le banc et pousse dans le talon pour élever le corps.\n4. Redescends en contrôlant et répète avec l''autre jambe.', 5, 1),
  (63, 'dumbbell-lunges', 'Fentes avec haltères', '1. Tiens un haltère dans chaque main, bras le long du corps.\n2. Fais un pas en avant avec une jambe en descendant le genou arrière vers le sol.\n3. Garde le buste droit et pousse dans le talon avant pour revenir à la position de départ.', 5, 2),
  (64, 'hip-abduction', 'Abducteurs à la machine', '1. Règle le siège et le dossier pour que tes genoux soient alignés avec l''axe des coussins.\n2. Assieds-toi et place les jambes contre les coussins extérieurs, pieds bien stables au sol.\n3. Pousse les coussins vers l''extérieur avec les jambes, buste droit et mouvement contrôlé.\n4. Reviens lentement à la position de départ sans laisser les coussins se refermer brutalement.', 5, 1),
  (65, 'hip-adduction', 'Adducteurs à la machine', '1. Règle le siège et les coussins pour qu''ils s''adaptent à tes jambes.\n2. Assieds-toi et place les jambes contre les coussins, bien alignés avec les genoux.\n3. Serre lentement les jambes l''une contre l''autre, en gardant le contrôle sur tout le mouvement.\n4. Reviens à la position de départ de façon contrôlée, sans laisser les coussins s''entrechoquer.', 5, 1),
  (66, 't-bar-row', 'Rowing en T', '1. Cale l''extrémité de la barre dans un angle de mur ou un support fixe.\n2. Charge l''autre extrémité avec le poids voulu et saisis-la à deux mains.\n3. Penche le buste vers l''avant en gardant le dos droit.\n4. Tire la barre vers la poitrine en serrant les omoplates, puis redescends lentement.', 2, 2),
  (67, 'skull-crusher', 'Barre au front', '1. Allonge-toi sur le dos sur un banc plat, en tenant une barre avec les mains écartées à largeur d''épaules.\n2. Tends les bras vers le haut en gardant les coudes légèrement fléchis.\n3. Descends lentement la barre vers ton front en contrôlant le mouvement.\n4. Reviens à la position de départ en tendant les bras sans verrouiller les coudes.', 4, 2),
  (68, 'preacher-curl', 'Curl au pupitre', '1. Règle le pupitre à une hauteur confortable et assieds-toi avec la poitrine en appui.\n2. Saisis la barre ou les haltères en prise supination, bras tendus.\n3. Fléchis les coudes pour monter la charge vers les épaules, en gardant les coudes fixes.\n4. Redescends lentement à la position de départ en contrôlant le mouvement.', 4, 1),
  (69, 'ski-erg', 'Machine à skier (SkiErg)', '1. Règle la résistance et saisis les poignées avec une prise ferme.\n2. Penche légèrement le buste vers l''avant en gardant le dos droit.\n3. Tire les poignées vers le bas et vers l''arrière en tendant les bras et en engageant le haut du dos et les triceps.\n4. Reviens lentement à la position de départ en contrôlant le mouvement.', 7, 2),
  (70, 'air-bike', 'Air bike (assault bike)', '1. Règle la hauteur de selle pour que tes pieds atteignent confortablement les pédales.\n2. Place tes mains sur les poignées et assieds-toi bien droit.\n3. Commence à pédaler en poussant et en tirant les poignées en même temps.\n4. Garde un rythme régulier et contrôle ta respiration.', 7, 1),
  (71, 'machine-hip-thrust', 'Hip thrust à la machine', '1. Règle la machine à ta taille et assieds-toi, dos bien calé contre le dossier.\n2. Place les pieds bien à plat au sol et ajuste le coussin sur tes hanches.\n3. Pousse vers le haut avec les hanches en serrant les fessiers en haut du mouvement.\n4. Redescends lentement les hanches à la position de départ en gardant le contrôle.', 5, 1),
  (72, 'sled-hack-squat', 'Hack squat sur chariot (45°)', '1. Place tes pieds sur la plateforme du chariot, écartés à largeur d''épaules.\n2. Déverrouille le chariot et descends lentement jusqu''à ce que tes genoux forment un angle de 90 degrés.\n3. Pousse dans les talons pour revenir à la position de départ, en gardant le dos droit.', 5, 2),
  (73, 'bicycle-crunch', 'Crunch bicyclette', '1. Allonge-toi sur le dos, mains derrière la tête et jambes décollées.\n2. Amène le coude droit vers le genou gauche en tendant la jambe droite.\n3. Alterne en amenant le coude gauche vers le genou droit, en gardant le rythme.', 6, 1),
  (74, 'push-ups', 'Pompes', '1. Place-toi face au sol, mains écartées à largeur d''épaules.\n2. Garde le corps aligné et descends jusqu''à ce que la poitrine frôle le sol.\n3. Pousse vers le haut jusqu''à tendre complètement les bras.', 1, 1),
  (75, 'cable-crossover', 'Écarté à la poulie haute', '1. Règle les poulies à hauteur d''épaules et choisis une charge adaptée.\n2. Prends une poignée dans chaque main et avance d''un pas, en gardant les coudes légèrement fléchis.\n3. Croise les mains devant toi en contractant les pectoraux, puis reviens lentement à la position de départ.', 1, 1),
  (76, 'chest-dips', 'Dips aux barres parallèles', '1. Attrape les barres parallèles, paumes tournées vers l''intérieur.\n2. Monte le corps jusqu''à avoir les bras tendus.\n3. Descends lentement le corps en te penchant légèrement vers l''avant.\n4. Pousse vers le haut pour revenir à la position de départ.', 1, 3),
  (77, 'decline-bench-press', 'Développé décliné à la barre', '1. Règle le banc en position déclinée et vérifie qu''il est bien bloqué.\n2. Allonge-toi sur le banc, pieds bien calés, et saisis la barre avec les mains un peu plus larges que les épaules.\n3. Descends la barre lentement vers la poitrine en gardant les coudes à 45 degrés.\n4. Pousse la barre vers le haut jusqu''à l''extension complète des bras, sans verrouiller les coudes.', 1, 2),
  (78, 'back-extension', 'Hyperextensions (extensions lombaires)', '1. Allonge-toi face contre le banc à lombaires, chevilles bien calées sous les rouleaux.\n2. Croise les bras sur la poitrine ou place-les derrière la tête.\n3. Remonte le buste lentement jusqu''à l''aligner avec les jambes, dos bien droit.\n4. Redescends en contrôlant jusqu''à la position de départ, sans cambrer le dos.', 2, 1),
  (79, 'dumbbell-pullover', 'Pull-over avec haltère', '1. Allonge-toi sur le dos sur un banc, pieds bien à plat au sol.\n2. Tiens un haltère à deux mains, bras tendus au-dessus de la poitrine.\n3. Descends lentement l''haltère derrière la tête en gardant les coudes légèrement fléchis.\n4. Reviens à la position de départ en contrôlant bien le mouvement.', 2, 2),
  (80, 'straight-arm-pulldown', 'Tirage bras tendus à la poulie', '1. Place-toi debout face à une poulie haute, pieds à largeur d''épaules.\n2. Saisis la barre à deux mains, bras tendus et coudes juste légèrement fléchis.\n3. Tire la barre vers le bas jusqu''à ce que tes mains arrivent aux cuisses, en gardant les bras tendus.\n4. Reviens lentement à la position de départ en contrôlant le mouvement.', 2, 1),
  (81, 'inverted-row', 'Tirage horizontal inversé', '1. Place une barre à hauteur de taille et allonge-toi dessous.\n2. Saisis la barre en pronation, bras tendus.\n3. Tire ta poitrine vers la barre en gardant le corps bien gainé et aligné.\n4. Redescends lentement jusqu''à la position de départ sans toucher le sol.', 2, 1),
  (82, 'barbell-shrug', 'Haussements d''épaules à la barre', '1. Tiens-toi bien droit, pieds à largeur d''épaules.\n2. Saisis la barre devant toi en pronation, mains un peu plus larges que les épaules.\n3. Monte les épaules vers les oreilles en gardant les bras tendus.\n4. Redescends les épaules lentement jusqu''à la position de départ.', 3, 1),
  (83, 'reverse-fly', 'Oiseau (deltoïde postérieur)', '1. 1. Mets-toi debout, pieds à largeur d''épaules, un haltère dans chaque main.\n2. 2. Penche légèrement le buste vers l''avant à partir des hanches, dos bien droit.\n3. 3. Bras légèrement fléchis, monte les haltères sur les côtés jusqu''à ce que les bras soient parallèles au sol.\n4. 4. Redescends lentement les haltères à la position de départ et recommence.', 3, 1),
  (84, 'front-raise', 'Élévations frontales', '1. Tiens-toi bien droit, pieds à largeur d''épaules.\n2. Tiens un haltère dans chaque main, bras tendus devant les cuisses.\n3. Monte les haltères vers l''avant jusqu''à ce que tes bras soient parallèles au sol.\n4. Redescends lentement les haltères jusqu''à la position de départ.', 3, 1),
  (85, 'arnold-press', 'Développé Arnold', '1. Assieds-toi sur un banc avec dossier, un haltère dans chaque main à hauteur des épaules, paumes tournées vers toi.\n2. Fais pivoter les paumes vers l''avant pendant que tu pousses les haltères vers le haut en décrivant un arc.\n3. Tends complètement les bras sans verrouiller les coudes, puis redescends lentement les haltères à la position de départ.', 3, 2),
  (86, 'concentration-curl', 'Curl concentré', '1. Assieds-toi au bord d''un banc, jambes écartées.\n2. Prends un haltère dans une main et cale ton coude contre l''intérieur de la cuisse.\n3. Fléchis le bras pour monter l''haltère vers l''épaule, coude bien fixe.\n4. Redescends lentement l''haltère à la position de départ et recommence.', 4, 1),
  (87, 'cable-curl', 'Curl à la poulie', '1. Règle la poulie en position basse et saisis la barre en supination.\n2. Tiens-toi bien droit, pieds à largeur d''épaules et coudes collés au corps.\n3. Fléchis les coudes pour monter la barre vers les épaules, coudes immobiles.\n4. Redescends lentement la barre à la position de départ en contrôlant le mouvement.', 4, 1),
  (88, 'triceps-kickback', 'Kickback triceps', '1. Prends un haltère dans chaque main, paumes tournées vers l''intérieur.\n2. Penche le buste vers l''avant en gardant le dos bien droit.\n3. Plie les coudes à 90 degrés, puis tends les bras vers l''arrière.\n4. Reviens lentement à la position de départ sans bouger les épaules.', 4, 1),
  (89, 'close-grip-bench-press', 'Développé couché prise serrée', '1. Allonge-toi sur un banc plat, pieds bien ancrés au sol.\n2. Saisis la barre en prise serrée, mains à hauteur des épaules.\n3. Descends la barre lentement vers la poitrine en gardant les coudes près du corps.\n4. Pousse la barre vers le haut jusqu''à tendre complètement les bras.', 4, 2),
  (90, 'wrist-curl', 'Curl de poignets', '1. Assieds-toi sur un banc, avant-bras posés sur les cuisses, un haltère dans chaque main, paumes vers le haut.\n2. Laisse les poignets dépasser au bord des genoux, bras immobiles.\n3. Fléchis les poignets vers le haut en montant les haltères le plus haut possible, puis redescends lentement à la position de départ.', 4, 1),
  (91, 'good-morning', 'Good morning à la barre', '1. Place les pieds à largeur d''épaules et garde le dos bien droit.\n2. Cale une barre sur tes épaules et vérifie qu''elle est bien équilibrée.\n3. Penche le buste vers l''avant à partir des hanches, jambes légèrement fléchies.\n4. Reviens à la position de départ en poussant avec les fessiers et les ischio-jambiers.', 5, 3),
  (92, 'sumo-deadlift', 'Soulevé de terre sumo', '1. Place les pieds plus larges que les épaules, pointes légèrement tournées vers l''extérieur.\n2. Saisis la barre mains à l''intérieur des jambes, dos bien droit.\n3. Soulève la barre en poussant les hanches et les genoux en extension jusqu''à te redresser complètement.', 5, 2),
  (93, 'nordic-curl', 'Curl nordique', '1. Cale bien tes chevilles sous un support ou demande à un partenaire de les maintenir.\n2. Pars à genoux, corps aligné des genoux à la tête.\n3. Descends lentement vers l''avant en contrôlant, jusqu''au point où tu ne peux plus retenir la chute.\n4. Amortis avec les mains, puis pousse légèrement pour revenir à la position de départ.', 5, 3),
  (94, 'cable-glute-kickback', 'Kickback fessier à la poulie', '1. Règle la poulie à la hauteur la plus basse et passe une cheville dans la sangle.\n2. Tiens-toi à la machine pour garder l''équilibre.\n3. Jambe tendue, pousse vers l''arrière jusqu''à sentir la contraction dans les fessiers.\n4. Reviens lentement à la position de départ sans laisser la charge reposer sur la pile.', 5, 1),
  (95, 'sissy-squat', 'Sissy squat', '1. Place les pieds à largeur d''épaules et garde le buste bien droit.\n2. Incline légèrement le buste vers l''arrière pendant que tu plies les genoux.\n3. Descends en contrôlant jusqu''à ce que les genoux soient presque à 90 degrés.\n4. Reviens à la position de départ en poussant avec les quadriceps.', 5, 3),
  (96, 'hanging-leg-raise', 'Relevé de jambes suspendu', '1. Attrape la barre de traction avec les mains à largeur d''épaules.\n2. Reste suspendu bras tendus et corps droit, sans te balancer.\n3. Monte les jambes serrées vers la poitrine en gardant le contrôle.\n4. Redescends les jambes lentement jusqu''à la position de départ.', 6, 3),
  (97, 'cable-crunch', 'Crunch à la poulie', '1. Règle la poulie en position haute et attrape la corde à deux mains.\n2. Mets-toi à genoux face à la machine, dos droit.\n3. Enroule le buste vers l''avant en amenant les coudes vers les genoux et en contractant les abdominaux.\n4. Reviens lentement à la position de départ en gardant le contrôle.', 6, 1),
  (98, 'mountain-climbers', 'Mountain climbers', '1. Place-toi en position de planche haute, mains juste sous les épaules.\n2. Ramène un genou vers la poitrine en gardant le corps aligné.\n3. Alterne les jambes rapidement, comme si tu courais sur place.\n4. Garde la sangle abdominale serrée et respire régulièrement pendant l''exercice.', 6, 1),
  (99, 'ab-wheel-rollout', 'Roue abdominale', '1. Mets-toi à genoux au sol, la roue abdominale tenue à deux mains.\n2. Penche le buste vers l''avant et fais rouler la roue lentement devant toi en gardant le dos droit.\n3. Arrête-toi dès que tu ne peux plus tenir la position correcte, puis reviens en roulant jusqu''à la position de départ.', 6, 3),
  (100, 'cable-woodchopper', 'Woodchopper à la poulie', '1. Règle la poulie en position haute et attrape la poignée à deux mains.\n2. Place-toi pieds à largeur d''épaules, buste tourné vers la poulie.\n3. Tire la poignée vers le bas en diagonale devant toi, en pivotant le buste et en fléchissant légèrement les genoux.\n4. Reviens lentement à la position de départ en contrôlant le mouvement.', 6, 2),
  (101, 'jump-rope', 'Corde à sauter', '1. 1. Tiens la corde à deux mains à hauteur des hanches.\n2. 2. Fais tourner la corde avec les poignets, pas avec les bras.\n3. 3. Saute légèrement quand la corde arrive vers tes pieds.\n4. 4. Garde un rythme régulier et retombe en souplesse sur la pointe des pieds.', 7, 2),
  (102, 'stair-climber', 'Simulateur d''escalier (stepmill)', '1. Place-toi face aux marches, pieds écartés à largeur d''épaules.\n2. Monte une marche avec le pied droit en poussant dans le talon pour activer les fessiers.\n3. Amène le pied gauche sur la même marche en gardant l''équilibre.\n4. Redescends en alternant les pieds et répète le mouvement.', 7, 1),
  (103, 'jumping-jacks', 'Jumping jacks', '1. Tiens-toi droit, pieds joints et bras le long du corps.\n2. Saute en écartant les jambes à largeur d''épaules tout en levant les bras au-dessus de la tête.\n3. Reviens à la position de départ en rapprochant les pieds et en baissant les bras.', 7, 1),
  (104, 'high-knees', 'Montées de genoux', '1. Tiens-toi droit, pieds à largeur d''épaules.\n2. Monte un genou vers la poitrine le plus haut possible.\n3. Alterne les genoux rapidement en accompagnant avec les bras.', 7, 1),
  (105, 'cable-shoulder-press', 'Développé épaules à la poulie', '1. Règle les poulies à hauteur d''épaules et saisis les poignées en prise pronation.\n2. Place-toi debout, pieds à largeur d''épaules et coudes légèrement fléchis.\n3. Pousse les poignées vers le haut jusqu''à tendre complètement les bras, en gardant le contrôle.\n4. Reviens lentement à la position de départ sans laisser les plaques s''entrechoquer.', 3, 1),
  (106, 'cable-upright-row', 'Tirage menton à la poulie', '1. Règle la poulie en position basse et attrape la poignée à deux mains.\n2. Tiens-toi droit, pieds à largeur d''épaules et sangle abdominale gainée.\n3. Tire la poignée vers le haut en ouvrant les coudes sur les côtés, plus haut que les mains.\n4. Redescends la poignée lentement à la position de départ en contrôlant le mouvement.', 3, 2),
  (107, 'cable-squat', 'Squat à la poulie', '1. Règle la poulie à la hauteur la plus basse et attrape la poignée à deux mains.\n2. Place-toi debout, pieds écartés à largeur d''épaules et dos droit.\n3. Descends en squat en envoyant les hanches vers l''arrière, genoux alignés avec les pieds.\n4. Remonte à la position de départ en poussant dans les talons et en gardant le contrôle du câble.', 5, 1),
  (108, 'bench-dips', 'Dips triceps sur banc', '1. Pose les mains sur le bord d''un banc, doigts vers l''avant et bras tendus.\n2. Fais glisser les fessiers vers l''avant, jambes tendues et talons au sol.\n3. Descends lentement le corps en pliant les coudes jusqu''à un angle de 90 degrés.\n4. Pousse sur les bras pour revenir à la position de départ.', 4, 1),
  (109, 'incline-dumbbell-curl', 'Curl incliné avec haltères', '1. Assieds-toi sur un banc incliné, un haltère dans chaque main.\n2. Laisse les bras pendre vers le bas, paumes tournées vers l''avant.\n3. Fléchis les coudes pour monter les haltères vers les épaules, en gardant les coudes près du buste.\n4. Redescends les haltères lentement à la position de départ en contrôlant le mouvement.', 4, 1),
  (110, 'dumbbell-shrug', 'Haussements d''épaules avec haltères', '1. Tiens-toi droit, pieds à largeur d''épaules.\n2. Tiens un haltère dans chaque main, bras tendus le long du corps.\n3. Monte les épaules vers les oreilles en gardant les bras tendus.\n4. Redescends les épaules lentement à la position de départ.', 3, 1),
  (111, 'cable-chest-press', 'Développé poitrine à la poulie', '1. Règle la hauteur des poulies au niveau de la poitrine et choisis la charge adaptée.\n2. Place-toi au centre, attrape les poignées paumes vers le bas et avance d''un pas.\n3. Coudes légèrement fléchis, pousse les poignées vers l''avant jusqu''à tendre les bras.\n4. Reviens lentement à la position de départ en contrôlant le mouvement.', 1, 1),
  (112, 'low-cable-fly', 'Écartés à la poulie basse (de bas en haut)', '1. Règle les poulies dans la position la plus basse et attrape les poignées paumes vers le haut.\n2. Avance d''un pas, buste légèrement penché en avant et pieds écartés à largeur d''épaules.\n3. Coudes légèrement fléchis, monte les poignées vers le haut et vers le centre du corps jusqu''à ce que les mains se rejoignent à hauteur de la poitrine.\n4. Reviens lentement à la position de départ en contrôlant le mouvement.', 1, 1),
  (113, 'cable-overhead-triceps-extension', 'Extension des triceps au-dessus de la tête à la poulie', '1. Règle la poulie en position haute et attrape la corde à deux mains.\n2. Place-toi debout, un pied devant l''autre pour être plus stable.\n3. Tends les bras vers le haut et vers l''avant en gardant les coudes près de la tête.\n4. Reviens lentement à la position de départ sans bouger les coudes.', 4, 1),
  (114, 'cable-front-raise', 'Élévations frontales à la poulie', '1. Règle la poulie en position basse et attrape la poignée à deux mains, paumes vers le bas.\n2. Place-toi debout, pieds à largeur d''épaules et genoux légèrement fléchis.\n3. Monte la poignée devant toi jusqu''à ce que les bras soient parallèles au sol, coudes légèrement fléchis.\n4. Redescends la poignée lentement à la position de départ en contrôlant le mouvement.', 3, 1),
  (115, 'cable-hip-abduction', 'Abduction de hanche à la poulie', '1. Règle la poulie basse à hauteur de ta cheville et fixe la sangle sur ta cheville extérieure.\n2. Place-toi de côté par rapport à la machine et tiens-toi d''une main pour garder l''équilibre.\n3. Avec la jambe équipée de la sangle, écarte vers l''extérieur sur le côté en gardant le buste droit.\n4. Reviens lentement à la position de départ et répète.', 5, 1),
  (116, 'cable-pullover', 'Pullover à la poulie', '1. Règle la poulie en position haute et saisis la corde à deux mains.\n2. Tiens-toi debout, pieds à largeur d''épaules, buste légèrement penché vers l''avant.\n3. Tire la corde vers le bas et vers ton corps en gardant les bras tendus, coudes légèrement fléchis.\n4. Reviens lentement à la position de départ en contrôlant le mouvement.', 2, 1),
  (117, 'wall-angels', 'Anges au mur', '1. Tiens-toi debout, dos contre le mur, pieds écartés à largeur d''épaules.\n2. Place les bras en ''W'', coudes et poignets en contact avec le mur.\n3. Fais glisser lentement les bras vers le haut pour former un ''Y'', en gardant le contact avec le mur.\n4. Redescends les bras à la position de départ et répète.', 8, 1),
  (118, 'cobra-stretch', 'Étirement du cobra', '1. Allonge-toi à plat ventre au sol, jambes tendues.\n2. Pose les paumes au sol à hauteur des épaules.\n3. Inspire et soulève lentement la poitrine en gardant les hanches au sol.\n4. Tiens la position 15 à 30 secondes, puis redescends doucement.', 8, 1),
  (119, 'dead-hang', 'Suspension à la barre (dead hang)', '1. 1. Trouve une barre de tractions et attrape-la en pronation, mains à largeur d''épaules.\n2. 2. Suspends-toi à la barre, bras complètement tendus et pieds décollés du sol.\n3. 3. Garde le corps droit et relâche les épaules, en laissant le poids étirer doucement le dos.\n4. 4. Tiens la position le temps voulu, en respirant de façon contrôlée.', 8, 1),
  (120, 'cat-cow', 'Chat-vache', '1. Mets-toi à quatre pattes, mains alignées sous les épaules et genoux sous les hanches.\n2. Inspire profondément en creusant le dos, tête et coccyx dirigés vers le plafond, pour entrer dans la position de la ''vache''.\n3. Expire en arrondissant le dos vers le haut, menton vers la poitrine et coccyx vers le bas, pour entrer dans la position du ''chat''.\n4. Enchaîne le cycle de façon fluide, en coordonnant la respiration avec chaque changement de position.', 8, 1),
  (121, 'dragon-flag', 'Drapeau du dragon', '1. Allonge-toi sur le dos sur un banc et agrippe le bord avec les mains.\n2. Monte les jambes et les hanches vers le haut en gardant le corps bien droit.\n3. Redescends lentement le corps sans toucher le banc, en contrôlant le mouvement.', 6, 3),
  (122, 'seated-barbell-wrist-curl', 'Curl de poignets assis à la barre', '1. Assieds-toi sur un banc, pieds bien ancrés au sol.\n2. Saisis la barre en supination, avant-bras posés sur les cuisses.\n3. Fléchis les poignets vers le haut en montant la barre le plus haut possible.\n4. Redescends lentement la barre à la position de départ en gardant le contrôle.', 4, 1),
  (123, 'behind-the-back-barbell-wrist-curl', 'Curl de poignets à la barre derrière le dos', '1. Debout, pieds écartés à largeur d''épaules, tiens la barre derrière toi, paumes vers l''arrière.\n2. Garde les bras tendus et monte la barre en fléchissant uniquement les poignets.\n3. Redescends lentement la barre à la position de départ en contrôlant le mouvement.', 4, 1),
  (124, 'dumbbell-wrist-curl-over-bench', 'Curl de poignets avec haltères sur banc', '1. Mets-toi à genoux derrière un banc plat et pose les deux avant-bras le long du banc, mains dans le vide au-delà du bord.\n2. Tiens un haltère dans chaque main, paumes vers le haut, et laisse les poignets tomber.\n3. Fléchis les poignets vers le haut sans décoller les avant-bras du banc.\n4. Redescends les haltères doucement jusqu''à la position de départ et répète.', 4, 1),
  (125, 'barbell-wrist-curl-over-bench', 'Curl de poignets à la barre sur banc', '1. Mets-toi à genoux derrière un banc plat et pose les deux avant-bras le long du banc, mains dans le vide au-delà du bord.\n2. Attrape la barre en supination, mains à largeur d''épaules, et laisse les poignets tomber.\n3. Monte la barre en fléchissant uniquement les poignets, avant-bras toujours collés au banc.\n4. Redescends la barre doucement jusqu''à la position de départ et répète.', 4, 1),
  (126, 'standing-barbell-reverse-wrist-curl', 'Curl de poignets inversé debout à la barre', '1. Debout, tiens la barre devant les cuisses en pronation (paumes vers l''arrière), mains à largeur d''épaules.\n2. Garde les coudes tendus et collés au corps : seuls les poignets bougent.\n3. Monte le dos des mains vers l''avant-bras en étendant les poignets et marque un temps d''arrêt en haut.\n4. Redescends la barre doucement jusqu''à relâcher les poignets et répète.', 4, 1),
  (127, 'bird-dog', 'Bird dog', '1. Mets-toi à quatre pattes, mains sous les épaules et genoux sous les hanches.\n2. Serre les abdominaux et garde le dos plat, le regard vers le sol.\n3. Tends en même temps un bras vers l''avant et la jambe opposée vers l''arrière, jusqu''à les amener à hauteur du dos.\n4. Reviens doucement à l''appui de départ et alterne le côté à chaque répétition.', 6, 1),
  (128, 'hollow-hold', 'Hollow hold', '1. Allonge-toi sur le dos et plaque le bas du dos au sol.\n2. Tends les bras derrière la tête et décolle les jambes tendues de quelques centimètres du sol.\n3. Décolle aussi la tête et les omoplates, pour former une banane avec ton corps.\n4. Tiens la position sans que le bas du dos se décolle du sol ; si c''est trop dur, plie les genoux.', 6, 2),
  (129, 'hollow-rock', 'Hollow rock', '1. Place-toi en position hollow : bas du dos plaqué au sol, bras tendus derrière la tête et jambes tendues décollées.\n2. Garde cette forme bien rigide et bascule vers l''arrière en emmenant les épaules vers le bas.\n3. Bascule vers l''avant en emmenant les hanches vers le bas et les épaules vers le haut, sans casser la position.\n4. Balance-toi en continu et de façon contrôlée, sans poser les pieds ni la tête.', 6, 2),
  (130, 'pallof-press', 'Développé Pallof', '1. Règle la poulie à hauteur de poitrine et place-toi de côté par rapport à elle, pieds à largeur de hanches.\n2. Tiens la poignée des deux mains contre le sternum et écarte-toi jusqu''à mettre le câble en tension.\n3. Tends les bras devant toi en résistant à la rotation qui te tire vers la poulie.\n4. Reviens doucement à la poitrine et répète ; change de côté à la fin de la série.', 6, 2),
  (131, 'farmers-walk', 'Marche du fermier', '1. Prends un haltère lourd d''une main et tiens-toi debout, poitrine haute et épaules en arrière.\n2. Serre les abdominaux pour ne pas pencher du côté chargé.\n3. Marche en ligne droite avec des pas courts et fermes, en gardant les épaules à la même hauteur.\n4. Parcours la distance prévue, change de main et répète.', 6, 1),
  (132, 'diamond-push-up', 'Pompes diamant', '1. Place-toi en position de pompes, mains jointes sous la poitrine, index et pouces formant un losange.\n2. Garde le corps bien droit de la tête aux talons et les abdominaux serrés.\n3. Descends la poitrine vers les mains en gardant les coudes près du corps.\n4. Pousse dans le sol jusqu''à tendre les bras, sans cambrer le bas du dos.', 1, 2),
  (133, 'wall-handstand', 'Poirier contre le mur', '1. Pose les mains au sol à une vingtaine de centimètres du mur, bras tendus et mains à largeur d''épaules.\n2. Monte les jambes d''un coup de pied contrôlé jusqu''à poser les talons contre le mur.\n3. Aligne mains, épaules et hanches à la verticale, abdominaux et fessiers serrés.\n4. Tiens la position en respirant régulièrement et redescends une jambe d''abord pour sortir.', 3, 3),
  (134, 'y-t-w-raise', 'Y-T-W au banc incliné', '1. Allonge-toi à plat ventre sur un banc incliné, un haltère léger dans chaque main et les bras qui pendent.\n2. Monte les bras tendus vers l''avant et vers le haut en formant un Y.\n3. Ouvre-les ensuite sur les côtés, à hauteur des épaules, en formant un T.\n4. Plie les coudes et ramène-les en arrière en formant un W, en serrant les omoplates, puis reviens au départ.', 8, 1),
  (135, 'chin-tuck', 'Rétraction du menton (chin tuck)', '1. Place-toi debout ou assis, dos droit et épaules relâchées.\n2. Fais glisser la tête vers l''arrière en rentrant le menton vers la gorge, comme pour te faire un double menton.\n3. Ne monte pas et ne baisse pas le regard : le mouvement est horizontal.\n4. Tiens deux à trois secondes puis reviens lentement à la position de départ.', 8, 1),
  (136, 'assisted-pistol-squat', 'Squat sur une jambe assisté', '1. Tiens-toi d''une main à un support stable et appuie-toi sur une seule jambe.\n2. Tends l''autre jambe devant toi, sans qu''elle touche le sol.\n3. Descends lentement en pliant le genou d''appui, talon collé au sol et poitrine haute.\n4. Pousse dans le talon pour remonter, en t''aidant juste ce qu''il faut avec le bras, puis change de jambe.', 5, 3),
  (137, 'deep-squat-hold', 'Squat profond maintenu', '1. Tiens-toi des deux mains à un support à hauteur de poitrine, les pieds un peu plus écartés que les épaules.\n2. Descends lentement jusqu''à ce que les hanches passent sous les genoux.\n3. Garde les talons au sol, les genoux ouverts et le buste redressé.\n4. Tiens la position en respirant profondément, puis remonte en t''aidant du support.', 8, 1),
  (138, 'hip-hinge-dowel', 'Charnière de hanche avec bâton', '1. Place un bâton à la verticale le long du dos, en contact avec la tête, le haut du dos et le sacrum.\n2. Tiens-le d''une main derrière la nuque et de l''autre derrière la taille.\n3. Envoie les hanches vers l''arrière et laisse le buste s''incliner, genoux légèrement fléchis.\n4. Descends tant que le bâton reste en contact avec les trois points, puis remonte en serrant les fessiers.', 8, 1),
  (139, 'hip-flexor-stretch', 'Étirement des fléchisseurs de hanche', '1. Pose un genou au sol et place l''autre pied devant, genou à 90 degrés.\n2. Rentre le bassin et serre le fessier de la jambe arrière.\n3. Pousse les hanches vers l''avant jusqu''à sentir l''étirement dans l''aine de la jambe à genoux.\n4. Monte le bras du même côté pour l''accentuer, tiens la position, puis change de jambe.', 8, 1),
  (140, 'low-lunge-rotation', 'Fente basse avec rotation', '1. Depuis une fente, genou arrière au sol, pose les deux mains à l''intérieur du pied avant.\n2. Garde la poitrine haute et la hanche arrière basse.\n3. Tourne le buste et monte le bras intérieur vers le plafond, en suivant la main du regard.\n4. Repose la main, répète plusieurs fois puis change de côté.', 8, 1),
  (141, 'figure-4-stretch', 'Étirement des fessiers (figure 4)', '1. Allonge-toi sur le dos, genoux pliés et pieds au sol.\n2. Croise une cheville sur le genou opposé pour former un quatre.\n3. Passe les mains derrière la cuisse d''appui et ramène-la vers la poitrine.\n4. Garde la tête et les épaules au sol, tiens la position puis change de côté.', 8, 1),
  (142, 'supine-hamstring-stretch', 'Étirement des ischio-jambiers allongé', '1. Allonge-toi sur le dos, une jambe tendue au sol.\n2. Passe une sangle ou une serviette sous la plante de l''autre pied et tiens-la à deux mains.\n3. Monte cette jambe tendue jusqu''à sentir la tension à l''arrière de la cuisse, sans plier le genou.\n4. Tiens en respirant puis redescends lentement ; change de jambe.', 8, 1),
  (143, 'seated-forward-fold', 'Flexion avant assis', '1. Assieds-toi au sol, jambes tendues et serrées, pointes de pieds vers toi.\n2. Grandis-toi depuis le sommet du crâne pour allonger le dos.\n3. Penche-toi depuis les hanches en amenant les mains vers les pieds, sans arrondir le dos.\n4. Va aussi loin que tu peux avec les genoux tendus et tiens la position en respirant.', 8, 1),
  (144, 'hip-90-90', 'Position 90/90 de hanche', '1. Assieds-toi au sol, une jambe devant et l''autre sur le côté, toutes les deux pliées à 90 degrés.\n2. Garde le buste redressé et pose les mains légèrement au sol.\n3. Tiens quelques secondes en sentant l''étirement dans les hanches.\n4. Bascule les deux genoux de l''autre côté pour changer de position, puis répète.', 8, 1),
  (145, 'calf-stretch-wall', 'Étirement des mollets au mur', '1. Pose les deux mains sur le mur à hauteur des épaules.\n2. Fais un grand pas en arrière avec une jambe, pied dans l''axe et talon au sol.\n3. Penche-toi vers le mur en pliant la jambe avant et en gardant celle de derrière tendue.\n4. Tiens la position en sentant l''étirement dans le mollet, puis change de jambe.', 8, 1),
  (146, 'ankle-dorsiflexion-wall', 'Dorsiflexion de cheville au mur', '1. Mets-toi à genoux face au mur et avance un pied à une vingtaine de centimètres de celui-ci.\n2. Pose les mains sur le mur ou sur le genou avant.\n3. Amène le genou vers le mur en le passant au-dessus des orteils, sans décoller le talon.\n4. Reviens en arrière et répète ; éloigne le pied si tu y arrives facilement, puis change de côté.', 8, 1),
  (147, 'thoracic-extension-bench', 'Extension thoracique sur banc', '1. Mets-toi à genoux face à un banc bas et pose les coudes dessus, mains jointes.\n2. Garde les hanches à l''aplomb des genoux et les abdominaux gainés.\n3. Enfonce la poitrine vers le sol en laissant le haut du dos s''étendre.\n4. Tiens quelques secondes en respirant profondément, puis reviens en position neutre.', 8, 1),
  (148, 'quadruped-thoracic-rotation', 'Rotation thoracique à quatre pattes', '1. Place-toi à quatre pattes et amène une main derrière la tête, coude ouvert.\n2. Tourne le buste en passant ce coude sous la poitrine, vers le bras d''appui.\n3. Ouvre ensuite le coude vers le plafond en tournant depuis le haut du dos et suis la main du regard.\n4. Garde les hanches immobiles au-dessus des genoux ; répète puis change de côté.', 8, 1),
  (149, 'open-book-stretch', 'Ouverture de poitrine allongé (livre ouvert)', '1. Allonge-toi sur le côté, genoux pliés à 90 degrés, l''un sur l''autre.\n2. Tends les deux bras joints devant toi, à hauteur des épaules.\n3. Ouvre le bras du dessus en demi-cercle vers le sol de l''autre côté, en tournant depuis le haut du dos.\n4. Garde les genoux posés, tiens quelques secondes puis change de côté.', 8, 1),
  (150, 'doorway-chest-stretch', 'Étirement des pectoraux dans l''encadrement de porte', '1. Pose l''avant-bras sur le montant de la porte, coude à hauteur d''épaule.\n2. Fais un pas en avant avec le pied du même côté.\n3. Tourne le buste du côté opposé jusqu''à sentir l''étirement dans les pectoraux.\n4. Tiens la position en respirant profondément, puis change de bras.', 8, 1),
  (151, 'lying-leg-raise', 'Relevé de jambes allongé', '1. Allonge-toi sur le dos, jambes serrées et tendues, bras le long du corps, paumes vers le sol.\n2. Plaque le bas du dos au sol et contracte les abdominaux avant de commencer.\n3. Monte les deux jambes tendues jusqu''à la verticale sans décoller les hanches du sol.\n4. Redescends lentement jusqu''à une vingtaine de centimètres du sol, sans les poser ni cambrer le dos.', 6, 1);

INSERT INTO exercise_muscle (exercise_id, muscle_group_id, role) VALUES
  (1, 1, 'primary'),
  (1, 2, 'secondary'),
  (1, 3, 'secondary'),
  (2, 1, 'primary'),
  (2, 2, 'secondary'),
  (2, 3, 'secondary'),
  (3, 1, 'primary'),
  (3, 2, 'secondary'),
  (4, 8, 'primary'),
  (4, 4, 'secondary'),
  (5, 8, 'primary'),
  (5, 4, 'secondary'),
  (6, 8, 'primary'),
  (6, 9, 'primary'),
  (6, 4, 'secondary'),
  (7, 8, 'primary'),
  (7, 9, 'primary'),
  (7, 4, 'secondary'),
  (8, 2, 'primary'),
  (8, 3, 'secondary'),
  (9, 2, 'primary'),
  (9, 3, 'secondary'),
  (10, 2, 'primary'),
  (11, 2, 'primary'),
  (11, 9, 'primary'),
  (11, 8, 'secondary'),
  (12, 4, 'primary'),
  (12, 5, 'secondary'),
  (13, 4, 'primary'),
  (13, 5, 'secondary'),
  (14, 3, 'primary'),
  (15, 3, 'primary'),
  (15, 1, 'secondary'),
  (15, 2, 'secondary'),
  (16, 12, 'primary'),
  (16, 11, 'primary'),
  (16, 13, 'secondary'),
  (16, 14, 'secondary'),
  (17, 13, 'primary'),
  (17, 11, 'secondary'),
  (18, 13, 'primary'),
  (18, 11, 'secondary'),
  (19, 12, 'primary'),
  (20, 11, 'primary'),
  (20, 13, 'secondary'),
  (21, 12, 'primary'),
  (21, 11, 'primary'),
  (21, 13, 'secondary'),
  (22, 12, 'primary'),
  (22, 11, 'primary'),
  (22, 6, 'secondary'),
  (22, 15, 'secondary'),
  (23, 14, 'primary'),
  (24, 6, 'primary'),
  (24, 7, 'secondary'),
  (24, 10, 'secondary'),
  (25, 7, 'primary'),
  (25, 6, 'secondary'),
  (26, 6, 'primary'),
  (26, 10, 'secondary'),
  (27, 8, 'primary'),
  (27, 4, 'secondary'),
  (28, 2, 'primary'),
  (28, 9, 'secondary'),
  (28, 4, 'secondary'),
  (29, 12, 'primary'),
  (29, 11, 'primary'),
  (29, 13, 'secondary'),
  (29, 14, 'secondary'),
  (30, 12, 'primary'),
  (30, 11, 'primary'),
  (30, 13, 'secondary'),
  (31, 1, 'primary'),
  (31, 2, 'secondary'),
  (31, 3, 'secondary'),
  (32, 1, 'primary'),
  (32, 2, 'secondary'),
  (32, 3, 'secondary'),
  (33, 1, 'primary'),
  (33, 2, 'secondary'),
  (33, 3, 'secondary'),
  (34, 1, 'primary'),
  (34, 2, 'secondary'),
  (35, 8, 'primary'),
  (35, 9, 'primary'),
  (35, 4, 'secondary'),
  (36, 8, 'primary'),
  (36, 4, 'secondary'),
  (37, 2, 'primary'),
  (37, 3, 'secondary'),
  (38, 2, 'primary'),
  (39, 4, 'primary'),
  (39, 5, 'secondary'),
  (40, 3, 'primary'),
  (41, 14, 'primary'),
  (42, 12, 'primary'),
  (42, 11, 'primary'),
  (42, 13, 'secondary'),
  (42, 14, 'secondary'),
  (42, 15, 'secondary'),
  (43, 12, 'primary'),
  (43, 11, 'primary'),
  (43, 13, 'secondary'),
  (44, 11, 'primary'),
  (44, 13, 'primary'),
  (44, 10, 'primary'),
  (44, 12, 'secondary'),
  (44, 9, 'secondary'),
  (44, 8, 'secondary'),
  (44, 5, 'secondary'),
  (45, 8, 'primary'),
  (45, 4, 'secondary'),
  (45, 5, 'secondary'),
  (46, 12, 'primary'),
  (46, 13, 'primary'),
  (46, 11, 'primary'),
  (46, 14, 'primary'),
  (47, 12, 'primary'),
  (47, 11, 'primary'),
  (47, 13, 'primary'),
  (47, 14, 'secondary'),
  (47, 2, 'secondary'),
  (48, 12, 'primary'),
  (48, 13, 'primary'),
  (48, 11, 'secondary'),
  (48, 14, 'secondary'),
  (49, 8, 'primary'),
  (49, 12, 'primary'),
  (49, 4, 'secondary'),
  (49, 13, 'secondary'),
  (49, 11, 'secondary'),
  (49, 5, 'secondary'),
  (50, 12, 'primary'),
  (50, 1, 'primary'),
  (50, 11, 'secondary'),
  (50, 2, 'secondary'),
  (50, 3, 'secondary'),
  (50, 6, 'secondary'),
  (51, 6, 'primary'),
  (52, 6, 'primary'),
  (52, 12, 'secondary'),
  (53, 6, 'primary'),
  (53, 12, 'secondary'),
  (54, 6, 'primary'),
  (54, 12, 'secondary'),
  (55, 7, 'primary'),
  (55, 6, 'primary'),
  (56, 11, 'primary'),
  (56, 13, 'secondary'),
  (56, 6, 'secondary'),
  (57, 7, 'primary'),
  (57, 6, 'primary'),
  (57, 2, 'secondary'),
  (58, 10, 'primary'),
  (58, 11, 'secondary'),
  (58, 2, 'secondary'),
  (59, 1, 'primary'),
  (59, 2, 'secondary'),
  (59, 3, 'secondary'),
  (60, 13, 'primary'),
  (60, 11, 'primary'),
  (60, 10, 'secondary'),
  (60, 5, 'secondary'),
  (61, 12, 'primary'),
  (61, 11, 'primary'),
  (61, 6, 'secondary'),
  (61, 8, 'secondary'),
  (62, 12, 'primary'),
  (62, 11, 'primary'),
  (62, 13, 'secondary'),
  (62, 14, 'secondary'),
  (63, 12, 'primary'),
  (63, 11, 'primary'),
  (63, 13, 'secondary'),
  (63, 14, 'secondary'),
  (63, 15, 'secondary'),
  (64, 11, 'primary'),
  (65, 15, 'primary'),
  (66, 8, 'primary'),
  (66, 4, 'secondary'),
  (66, 5, 'secondary'),
  (66, 9, 'secondary'),
  (67, 3, 'primary'),
  (68, 4, 'primary'),
  (68, 5, 'secondary'),
  (69, 8, 'primary'),
  (69, 3, 'primary'),
  (69, 6, 'secondary'),
  (69, 2, 'secondary'),
  (69, 12, 'secondary'),
  (70, 12, 'primary'),
  (70, 13, 'primary'),
  (70, 8, 'primary'),
  (70, 2, 'secondary'),
  (70, 4, 'secondary'),
  (70, 3, 'secondary'),
  (70, 6, 'secondary'),
  (71, 11, 'primary'),
  (71, 13, 'secondary'),
  (71, 12, 'secondary'),
  (72, 12, 'primary'),
  (72, 11, 'primary'),
  (72, 13, 'secondary'),
  (73, 6, 'primary'),
  (73, 7, 'primary'),
  (74, 1, 'primary'),
  (74, 2, 'secondary'),
  (74, 3, 'secondary'),
  (75, 1, 'primary'),
  (75, 2, 'secondary'),
  (76, 1, 'primary'),
  (76, 3, 'secondary'),
  (76, 2, 'secondary'),
  (77, 1, 'primary'),
  (77, 3, 'secondary'),
  (78, 10, 'primary'),
  (78, 11, 'secondary'),
  (78, 13, 'secondary'),
  (79, 8, 'primary'),
  (79, 1, 'secondary'),
  (79, 3, 'secondary'),
  (80, 8, 'primary'),
  (80, 3, 'secondary'),
  (81, 8, 'primary'),
  (81, 4, 'secondary'),
  (81, 5, 'secondary'),
  (82, 9, 'primary'),
  (82, 5, 'secondary'),
  (83, 2, 'primary'),
  (83, 8, 'secondary'),
  (83, 9, 'secondary'),
  (84, 2, 'primary'),
  (85, 2, 'primary'),
  (85, 3, 'secondary'),
  (86, 4, 'primary'),
  (86, 5, 'secondary'),
  (87, 4, 'primary'),
  (87, 5, 'secondary'),
  (88, 3, 'primary'),
  (89, 3, 'primary'),
  (89, 1, 'secondary'),
  (89, 2, 'secondary'),
  (90, 5, 'primary'),
  (91, 13, 'primary'),
  (91, 11, 'secondary'),
  (91, 10, 'secondary'),
  (92, 11, 'primary'),
  (92, 13, 'primary'),
  (92, 12, 'secondary'),
  (92, 15, 'secondary'),
  (92, 10, 'secondary'),
  (93, 13, 'primary'),
  (93, 11, 'secondary'),
  (94, 11, 'primary'),
  (94, 13, 'secondary'),
  (95, 12, 'primary'),
  (96, 6, 'primary'),
  (96, 5, 'secondary'),
  (96, 7, 'secondary'),
  (97, 6, 'primary'),
  (98, 6, 'primary'),
  (98, 12, 'secondary'),
  (98, 2, 'secondary'),
  (99, 6, 'primary'),
  (99, 7, 'secondary'),
  (100, 7, 'primary'),
  (100, 6, 'secondary'),
  (101, 14, 'primary'),
  (101, 12, 'secondary'),
  (101, 2, 'secondary'),
  (102, 12, 'primary'),
  (102, 11, 'primary'),
  (102, 13, 'secondary'),
  (102, 14, 'secondary'),
  (103, 2, 'primary'),
  (103, 12, 'secondary'),
  (103, 14, 'secondary'),
  (104, 12, 'primary'),
  (104, 6, 'secondary'),
  (104, 14, 'secondary'),
  (105, 2, 'primary'),
  (105, 3, 'secondary'),
  (106, 2, 'primary'),
  (106, 9, 'secondary'),
  (106, 4, 'secondary'),
  (107, 12, 'primary'),
  (107, 11, 'secondary'),
  (107, 13, 'secondary'),
  (108, 3, 'primary'),
  (108, 2, 'secondary'),
  (108, 1, 'secondary'),
  (109, 4, 'primary'),
  (109, 5, 'secondary'),
  (110, 9, 'primary'),
  (110, 2, 'secondary'),
  (111, 1, 'primary'),
  (111, 2, 'secondary'),
  (111, 3, 'secondary'),
  (112, 1, 'primary'),
  (112, 2, 'secondary'),
  (113, 3, 'primary'),
  (114, 2, 'primary'),
  (115, 11, 'primary'),
  (116, 8, 'primary'),
  (116, 1, 'secondary'),
  (116, 3, 'secondary'),
  (117, 2, 'primary'),
  (117, 8, 'secondary'),
  (117, 9, 'secondary'),
  (118, 10, 'primary'),
  (118, 6, 'secondary'),
  (119, 8, 'primary'),
  (119, 5, 'secondary'),
  (119, 2, 'secondary'),
  (120, 10, 'primary'),
  (120, 6, 'secondary'),
  (121, 6, 'primary'),
  (121, 7, 'secondary'),
  (121, 10, 'secondary'),
  (122, 5, 'primary'),
  (123, 5, 'primary'),
  (124, 5, 'primary'),
  (125, 5, 'primary'),
  (126, 5, 'primary'),
  (127, 6, 'primary'),
  (127, 10, 'secondary'),
  (127, 11, 'secondary'),
  (128, 6, 'primary'),
  (128, 12, 'secondary'),
  (129, 6, 'primary'),
  (129, 7, 'secondary'),
  (130, 7, 'primary'),
  (130, 6, 'secondary'),
  (130, 2, 'secondary'),
  (131, 7, 'primary'),
  (131, 9, 'secondary'),
  (131, 5, 'secondary'),
  (132, 3, 'primary'),
  (132, 1, 'secondary'),
  (132, 2, 'secondary'),
  (133, 2, 'primary'),
  (133, 3, 'secondary'),
  (133, 9, 'secondary'),
  (134, 2, 'primary'),
  (134, 8, 'secondary'),
  (134, 9, 'secondary'),
  (135, 9, 'primary'),
  (135, 8, 'secondary'),
  (136, 12, 'primary'),
  (136, 11, 'secondary'),
  (136, 13, 'secondary'),
  (137, 12, 'primary'),
  (137, 11, 'secondary'),
  (137, 15, 'secondary'),
  (138, 13, 'primary'),
  (138, 11, 'secondary'),
  (138, 10, 'secondary'),
  (139, 12, 'primary'),
  (139, 11, 'secondary'),
  (140, 12, 'primary'),
  (140, 11, 'secondary'),
  (140, 7, 'secondary'),
  (141, 11, 'primary'),
  (141, 10, 'secondary'),
  (142, 13, 'primary'),
  (142, 14, 'secondary'),
  (143, 13, 'primary'),
  (143, 10, 'secondary'),
  (144, 11, 'primary'),
  (144, 15, 'secondary'),
  (145, 14, 'primary'),
  (146, 14, 'primary'),
  (147, 8, 'primary'),
  (147, 1, 'secondary'),
  (148, 8, 'primary'),
  (148, 7, 'secondary'),
  (149, 8, 'primary'),
  (149, 1, 'secondary'),
  (149, 7, 'secondary'),
  (150, 1, 'primary'),
  (150, 2, 'secondary'),
  (151, 6, 'primary'),
  (151, 7, 'secondary'),
  (151, 12, 'secondary');

INSERT INTO exercise_equipment (exercise_id, equipment_id) VALUES
  (1, 1),
  (2, 1),
  (3, 1),
  (4, 1),
  (5, 1),
  (6, 1),
  (7, 2),
  (8, 3),
  (9, 1),
  (10, 3),
  (11, 2),
  (12, 3),
  (13, 3),
  (14, 2),
  (15, 1),
  (16, 1),
  (17, 1),
  (18, 1),
  (19, 1),
  (20, 4),
  (21, 5),
  (22, 3),
  (23, 1),
  (24, 5),
  (25, 5),
  (26, 5),
  (27, 1),
  (28, 4),
  (29, 4),
  (30, 3),
  (31, 4),
  (32, 3),
  (33, 3),
  (34, 3),
  (35, 4),
  (36, 3),
  (37, 4),
  (38, 2),
  (39, 4),
  (40, 3),
  (41, 4),
  (42, 5),
  (43, 1),
  (44, 4),
  (45, 5),
  (46, 6),
  (47, 6),
  (48, 6),
  (49, 6),
  (50, 5),
  (51, 5),
  (52, 5),
  (53, 5),
  (54, 5),
  (55, 5),
  (56, 5),
  (57, 5),
  (58, 5),
  (59, 4),
  (60, 4),
  (61, 4),
  (62, 3),
  (63, 3),
  (64, 1),
  (65, 1),
  (66, 4),
  (67, 4),
  (68, 4),
  (69, 6),
  (70, 6),
  (71, 1),
  (72, 1),
  (73, 5),
  (74, 5),
  (75, 2),
  (76, 5),
  (77, 4),
  (78, 5),
  (79, 3),
  (80, 2),
  (81, 5),
  (82, 4),
  (83, 3),
  (84, 3),
  (85, 3),
  (86, 3),
  (87, 2),
  (88, 3),
  (89, 4),
  (90, 3),
  (91, 4),
  (92, 4),
  (93, 5),
  (94, 2),
  (95, 5),
  (96, 5),
  (97, 2),
  (98, 5),
  (99, 5),
  (100, 2),
  (101, 5),
  (102, 6),
  (103, 5),
  (104, 5),
  (105, 2),
  (106, 2),
  (107, 2),
  (108, 5),
  (109, 3),
  (110, 3),
  (111, 2),
  (112, 2),
  (113, 2),
  (114, 2),
  (115, 2),
  (116, 2),
  (117, 5),
  (118, 5),
  (119, 5),
  (120, 5),
  (121, 5),
  (122, 4),
  (123, 4),
  (124, 3),
  (125, 4),
  (126, 4),
  (127, 5),
  (128, 5),
  (129, 5),
  (130, 2),
  (131, 3),
  (132, 5),
  (133, 5),
  (134, 3),
  (135, 5),
  (136, 5),
  (137, 5),
  (138, 5),
  (139, 5),
  (140, 5),
  (141, 5),
  (142, 5),
  (143, 5),
  (144, 5),
  (145, 5),
  (146, 5),
  (147, 5),
  (148, 5),
  (149, 5),
  (150, 5),
  (151, 5);

COMMIT;
